-- Add missing fields to GameMedia table
ALTER TABLE "GameMedia" ADD COLUMN IF NOT EXISTS "width" INTEGER;
ALTER TABLE "GameMedia" ADD COLUMN IF NOT EXISTS "height" INTEGER;
ALTER TABLE "GameMedia" ADD COLUMN IF NOT EXISTS "duration" INTEGER;
ALTER TABLE "GameMedia" ADD COLUMN IF NOT EXISTS "approved" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "GameMedia" ADD COLUMN IF NOT EXISTS "uploadedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP; 