import { ReactNode } from 'react'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

interface DashboardLayoutProps {
  children: ReactNode
}

export default function DashboardLayout({ children }: DashboardLayoutProps) {
  return (
    <div className="min-h-screen bg-background">
      <main>
        {children}
      </main>
    </div>
  )
}
