import { ReactNode } from 'react'
import NavBar from '@/components/layout/nav-bar';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

interface DashboardLayoutProps {
  children: ReactNode
}

export default function DashboardLayout({ children }: DashboardLayoutProps) {
  return (
    <div className="min-h-screen bg-background">
      <NavBar />
      <main className="container mx-auto py-6">
        {children}
      </main>
    </div>
  )
}
