import React from 'react';
import NavBar from '@/components/layout/nav-bar';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function DashboardLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="min-h-screen bg-gray-50">
      <NavBar />
      <main className="container mx-auto py-6">
        {children}
      </main>
    </div>
  );
}
